version: '3.4'
services:
  db:
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: pas154304
      MYSQL_USER: root
      MYSQL_PASSWORD: pas154304
      MYSQL_DATABASE: db_social_food
    ports:
      - "3308:3306"
    networks: 
      - generation-network
  socialfood:
    restart: always
    build: ./socialfood
    working_dir: /socialfood
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Production
    volumes:
      - ./socialfood:/socialfood
      - ~/.m2:/root/.m2
    ports:
      - "9000:8080"
    command: mvn clean spring-boot:run
    links:
      - db
    depends_on:
      - db
    networks:
      - generation-network
networks:
  generation-network:
    driver: bridge